### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by shin2jhoon** [jyoungrok/ShareCam_Parse#2]
Is it work?

**Comment by y-rok** [comment]
## NAVER - http://www.naver.com/

jyr3357@naver.com 님께 보내신 메일 <[ShareCam_Parse] Hello? (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---

**Comment by shin2jhoon** [comment]
...
